server:
  port: 9000
spring:
  application:
    name: gate-way-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    eureka-consumer: /eureka-consumer/**
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

